name: Auto Approve

on:
  pull_request:
    branches: [ develop, stage01 ]
  workflow_dispatch:

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
