name: Create PullRequest

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  pullrequest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: master to develop
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "master to develop"

      - name: master to stage01
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "stage01"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: "master to stage01"
