# This is a basic workflow to help you get started with Actions

name: distribute_master

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  distribute:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:          
      - name: master_to_develop
        uses: devmasx/merge-branch@1.4.0
        with:
          # The name of target branch to merge
          target_branch: develop
          # Alias head_to_merge input
          from_branch: master
          # Github token
          github_token: ${{ secrets.GITHUB_TOKEN }}
